server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

storage:
  trace:
    backend: local                     
    wal:
      path: /tmp/tempo/wal             
    local:
      path: /tmp/tempo/blocks

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 168h                # Retain traces for 7 days (168 hours)
    compacted_block_retention: 10m
